version: 0.2

phases: 
  install: 
    commands: 
      - echo Installing Node 12...
      - curl -sL https: cinst nodejs.install
      - echo Installing yarn...
      - choco install yarn
  pre_build: 
    commands: 
      - echo Installing yarn dependencies
      - yarn
  build: 
    commands:
      - echo Testing...
      - yarn test
      - echo Building...
      - yarn build
artifacts: 
  files: 
    - "**/*"
  discard-paths: no 
  base-directory: dist