const Common = {
    position: 'Position',
    size: 'Size',
    rotation: 'Rotation',
    color: 'Color',
    zoom: 'Zoom',
    exit: 'Exit',
    shape: 'Shape',
    display: 'Display',
    shapes: 'Shapes',
    background: 'Background',
    clear: 'Clear',
    save: 'Save',
    palette: 'Palette',
    colorPalette: 'Color Palette',
    layers: 'Layers',
    topPanel: 'Top Panel',
    sidePanel: 'Side Panel',
    type: 'Type',
    border: 'Border',
    square: 'Square',
    circle: 'Circle',
    width: 'Width',
    height: 'Height',
    radius: 'Radius',
    zoom: 'Zoom',
    stamp: 'Stamp',
    radius: 'Radius',
    selectCurrentShape: 'Select Current Shape'
}

export default Common;