const Common = {
    position: 'Position',
    size: 'Size',
    rotation: 'Rotation',
    color: 'Color',
    zoom: 'Zoom',
    exit: 'Exit',
    shape: 'Shape',
    display: 'Display',
    shapes: 'Shapes',
    background: 'Background',
    clear: 'Clear',
    save: 'Save',
    palette: 'Palette',
    colorPalette: 'Color Palette',
    layers: 'Layers',
    topPanel: 'Top Panel',
    sidePanel: 'Side Panel',
    type: 'Type',
    border: 'Border',
    square: 'Square',
    circle: 'Circle',
    width: 'Width',
    height: 'Height',
    radius: 'Radius',
    stamp: 'Stamp',
    selectCurrentShape: 'Select Current Shape',
    positionX: 'Position X',
    positionY: 'Position Y',
    posX: 'Pos X',
    posY: 'Pos Y',
    line: 'Line',
    stroke: 'Stroke',
    strokeWidth: 'Stroke Width',
    numberOfPoints: 'Number of Points'
}

export default Common;